server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0

management:
  tracing:
    sampling.probability: 1.0
  endpoint:
    metrics.enabled: true
    prometheus.enabled: true
  endpoints.web.exposure.include:
    - prometheus
  metrics.export:
    prometheus.enabled: true
  zipkin.tracing.endpoint: http://zipkin:9411/api/v2/spans